# Active Profile
spring:
  profiles:
    active: default

  # Jackson Settings
  jackson:
    time-zone: America/Toronto
    date-format: "yyyy-MM-dd"
    deserialization:
      fail-on-unknown-properties: false      
      
  # Email Settings
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          debug: true
          transport:
            protocol: smtp

  # Common Database Settings
  sql:
    init:
      continue-on-error: false

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # File upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:2?Q:mba;7mvN[^0=Ixw54z@YOiySC!TqGF)-20tOL`*qs^AlK_|gYoS;ah0r2Oj}
  expiration: 3600000
---
# Default Profile Settings
spring:
  config:
    activate:
      on-profile: default
  
  server:
    port: ${PORT:8080}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update

# Python Flask service configuration
python:
  flask:
    base-url: ${FLASK_BASE_URL}