# Active Profile
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default} # Default to 'default' if not set

  # Jackson Settings
  jackson:
    time-zone: ${JACKSON_TIMEZONE:America/Toronto}
    date-format: ${JACKSON_DATE_FORMAT:yyyy-MM-dd}
    deserialization:
      fail-on-unknown-properties: ${JACKSON_FAIL_ON_UNKNOWN:false}      

  # Email Settings
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}
            required: ${MAIL_STARTTLS_REQUIRED:true}
          debug: ${MAIL_DEBUG:true}
          transport:
            protocol: ${MAIL_TRANSPORT_PROTOCOL:smtp}

  # Common Database Settings
  sql:
    init:
      continue-on-error: ${SQL_CONTINUE_ON_ERROR:false}

  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ${JPA_SHARED_CACHE_MODE:ENABLE_SELECTIVE}
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
    hibernate:
      naming:
        physical-strategy: ${HIBERNATE_NAMING_STRATEGY:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl}

  # File upload configuration
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:10MB}
      enabled: ${MULTIPART_ENABLED:true}

---
# Default Profile Settings
spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:5}
      minimum-idle: ${DB_MIN_IDLE:2}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}

# Python Flask service configuration
python:
  flask:
    base-url: ${PYTHON_FLASK_BASE_URL:http://localhost:5000}
